# Generated by Django 5.1.4 on 2025-01-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('sobrenome', models.TextField(max_length=255)),
                ('sexo', models.CharField(max_length=1)),
                ('cep', models.TextField(max_length=255)),
                ('rua', models.TextField(max_length=255)),
                ('numero', models.TextField(max_length=255)),
                ('complemento', models.TextField(max_length=255)),
                ('bairro', models.TextField(max_length=255)),
                ('cidade', models.TextField(max_length=255)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
    ]
