# Generated by Django 5.1.4 on 2025-01-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to='')),
                ('descricao', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
