# Generated by Django 5.1.4 on 2025-01-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
